name: Deploy React App
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test App
        run: npm run test
      - name: Lint App
        run: npm run lint
      - name: Build App
        run: npm run build
      - name: Deploy
        run: echo Deploying...